Fix old regex
"Error fix"

NSRegularExpression(#"ytplayer\.config\s*=\s*(\{)"#), ---> Seems to be outdated. Hence commented out

Failed to decode object from given start point:
pattern (ytplayer\.config\s*=\s*) failed: （YouTubeKit.YouTubeKitError1）
applying descrambler
YouTubeKit/RegularExpression.swift:16: Fatal error: Illegal regular expression var (\w+)={[^}]+}